### ISSUE TITLE
Claws Require Testing

### ISSUE THREAD

**Issue by ChthonVII** [ChthonVII/d2r_24ptr2_wereform_calculator#4]
Presently the calculator takes the unusual animationspeed for claws into consideration when computing the slowing factor. This is a guess because it's the sensible way to do it. However, it's possible that Blizzard neglected this case and just used 256 across the board. Some empirical data points would be much appreciated.

**Comment by Warren1001** [comment]
Claw's 208 animationspeed is used in all cases, being for animationspeed for nerffactor, animationspeed_human for nerffactor, and animationspeed for increment. I tested Werebear Normal Attack on an Assassin wielding one Suwayyah (0 WSM), modified Burst of Speed to give attackrate = lvl, Werebear gave no attackrate, made sure to adjust Burst of Speed outside of wereform, and found the following breakpoints (switch to the Claw page): https://docs.google.com/spreadsheets/d/1eo3VeIrSG3PvE0woLRqtG3tofafjaXEaBDsCU0uETvU/edit#gid=107327619
I stopped testing pretty early under the assumption that it was simply going to work that way. Any time I modified any of the 3 values to 256, I got widely different breakpoints that didn't match, so I don't think theres an alternative calculation where we would have 'off by 1' issues.

**Comment by ChthonVII** [comment]
So the human animationspeed is getting used directly in wereform -- that's one possibility I didn't consider!

Also, since the human animationspeed is appearing in both the numerator and denominator of the nerf factor, it should drop out entirely. So nerf factor is just wereform_A1_framesperdirection / human_A1_framesperdirection.

Only one question remains, which I noted over in the bite issue. (It is relevant only to modders.)
